name: arp242.net
url: http://arp242.net
author: Martin Tournoij
excerpt_separator: 
highlighter: null
permalink: /weblog/:title.html
exclude: [comments, old, vendor, Gemfile, Gemfile.lock, mkcode.lua, new.arp242.net]
markdown: kramdown
