name: "arp242.net"
url: "https://www.arp242.net"
author: "Martin Tournoij"
excerpt_separator: 
highlighter: none
permalink: "/:title.html"
markdown: "kramdown"
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "README.markdown",
  "the-art-of-unix-programming/base.css",
  "the-art-of-unix-programming/base.js",
  "the-art-of-unix-programming/hello-css.min.css",
  "the-art-of-unix-programming/readon.js"]

# Copy for Netlify.
include: ["_redirects", ".well-known"]

# Always publish all posts, some posts may be considered in the "future" by the
# deploy pipline as that's in the US, but I'm in New Zealand, so that's almost a
# full day behind.
future: true
