name: arp242.net
url: https://arp242.net
author: Martin Tournoij
excerpt_separator: 
highlighter: null
permalink: /weblog/:title.html
exclude: [Gemfile, Gemfile.lock, mkcode.go]
markdown: kramdown
plugins:
  - liquid_reading_time
