name:         'arp242.net'
url:          'https://www.arp242.net'
author:       'Martin Tournoij'
markdown:     'kramdown'
highlighter:  'none'
includes_dir: ''
excerpt_separator: 'xxxxxx'
strict_front_matter: true

collections:
  posts: { output: true }
  text:  { output: true }
defaults:
  -
    scope:  { path: '_posts' }
    values: { layout: 'post', permalink: '/:title.html' }
  -
    scope:  { path: '_text' }
    values: { layout: 'post_text', permalink: '/:title.txt' }

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "README.markdown",
  "the-art-of-unix-programming/base.css",
  "the-art-of-unix-programming/base.js",
  "the-art-of-unix-programming/hello-css.min.css",
  "the-art-of-unix-programming/readon.js",
  '.vim-hl']

# Copy for Netlify.
include: ["_redirects", ".well-known"]

# Always publish all posts, some posts may be considered in the "future" by the
# deploy pipline as that's in the US, but I'm in New Zealand, so that's almost a
# full day behind.
future: true
