name: arp242.net
url: https://arp242.net
author: Martin Tournoij
excerpt_separator: 
highlighter: none
permalink: /weblog/:title.html
exclude: [Gemfile, Gemfile.lock, mkcode.go]
markdown: kramdown

# Always publish all posts, some posts may be considered in the "future" by the
# deploy pipline as that's in the US, but I'm in New Zealand, so that's almost a
# full day behind.
future: true
