[[headers]]
	# Fonts are not going to change, cache them so navigating is more smooth
	# since the browser won't have to revalidate.
	for = "*.woff2"
	[headers.values]
		Cache-Control = "public, max-age=7776000"  # 90 days
